title: CLOAKmatch
description: Private set-style syncing of indicators via Ristretto255 OPRF

# Minimal Mistakes Jekyll theme with dark skin
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark

logo: CLOAKmatch.png

search: true

plugins:
  - jekyll-seo-tag

# Use single-column layout with page ToC by default
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      toc: true
      toc_sticky: true

exclude:
  - README.md
