title: CLOAKmatch
description: Private set-style syncing via Ristretto255 OPRF
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
