title: CLOAKmatch
description: Private set-style syncing via Ristretto255 OPRF
remote_theme: mmistakes/minimal-mistakes
logo: /CLOAKmatch.png
permalink: pretty
skin: dark
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Defaults: use docs layout and shared sidebar
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: docs
      sidebar:
        title: Documentation
        nav: docs
