title: CLOAKmatch
description: Private set-style syncing of indicators via Ristretto255 OPRF
remote_theme: just-the-docs/just-the-docs
color_scheme: light

logo: CLOAKmatch.png
favicon_ico: CLOAKmatch.png

search_enabled: true
heading_anchors: true
aux_links:
  View on GitHub: https://github.com/your-user-or-org/your-repo

nav_external_links:
  - title: PyPI libsodium (install)
    url: https://doc.libsodium.org/installation
    hide_icon: false

footer_content: "Copyright © {{ site.time | date: '%Y' }}"

plugins:
  - jekyll-seo-tag

exclude:
  - README.md

